[package]
name = "frontend"
version = "0.1.0"
edition = "2024"

[dependencies]
env_logger = "0.10"
log = "0.4"
rustic = { path = "../rustic", features = ["meta"], default-features = false }
sdl2 = { version = "0.37.0", features = ["image", "ttf"] }
