// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FrequencyData } from "./FrequencyData";

export type AnalysisBin = { 
/**
 * The first sample index of the bin
 */
sample_index: number, 
/**
 * The amount of samples analysed in the bin
 */
bin_size: number, peak_frequency: number, frequencies: Array<FrequencyData>, rms_level: number, pitch: number | null, note: string | null, };
