// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Summary of a fully analyzed audio file (Phase 1 response).
 */
export type AudioSummary = { sample_rate: number, duration: number, channels: number, total_samples: number, peak_frequency: number, rms_level: number, pitch: number | null, note: string | null, };
