// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FrequencyData } from "./FrequencyData";

/**
 * Frequency spectrum (FFT) for a time window (Phase 2 response).
 */
export type SpectrumData = { frequencies: Array<FrequencyData>, 
/**
 * Global top frequency peaks (sorted by magnitude descending, min 50 Hz separation).
 */
top_frequencies: Array<FrequencyData>, start_time: number, end_time: number, };
