// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Waveform data for a time window (Phase 2 response).
 * If `downsampled` is true, `samples` contains interleaved [min, max, min, max, ...] pairs.
 */
export type WaveformData = { samples: Array<number>, start_time: number, end_time: number, sample_rate: number, downsampled: boolean, };
