[project]
name = "rustic-devel"
description = "A development environment for prototyping rustic features"
readme = "README.md"
requires-python = ">=3.10"
version = "0.1.0"
dependencies = [
    "jupyter>=1.1.1",
    "matplotlib>=3.9.2",
    "numpy>=2.1.3",
    "typing-extensions>=4.12.2",
]
