// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Parameter } from "./Parameter";

/**
 * One connectable input port off a filter
 * Port index = position in FilterInfo::inputs
 */
export type FilterInput = { label: string | null, parameter: Parameter<string> | null, };
