// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FilterInput } from "./FilterInput";

/**
 * Static metadata describing a filter type.
 */
export type FilterInfo = { name: string, type_id: string, description: string, 
/**
 * All input ports in port-index orde: audio inputs first, then parameter ports
 */
inputs: Array<FilterInput>, 
/**
 * Number of output ports
 */
outputs: number, };
