// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Parameter } from "./Parameter";

/**
 * Static metadata describing a filter type.
 */
export type FilterInfo = { name: string, description: string, source_amount: number, parameters: Array<Parameter<string>>, };
