// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Determines the size of a List parameter.
 */
export type ListSize<S> = { "Field": S } | { "Constant": number };
