// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Represents a literal value that defines a List parameter's type.
 */
export type Literal = { "Toggle": [string, boolean] } | { "Range": [string, number, number, number] } | { "Float": [string, number] } | { "Int": [string, number, number | null, number | null] };
