// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Parameter } from "./Parameter";

export type MetaGenerator = { 
/**
 * Human-readable display name shown in the graph editor.
 */
name: string, 
/**
 * Machine-readable identifier sent to the backend when adding a node.
 */
type_id: string, description: string, parameters: Array<Parameter<string>>, output_count: number, };
