// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ListSize } from "./ListSize";
import type { Literal } from "./Literal";

export type Parameter<S> = { "Toggle": { title: S, field_name: S, default: boolean, value: boolean, } } | { "Range": { title: S, field_name: S, min: number, max: number, default: number, value: number, } } | { "Float": { title: S, field_name: S, default: number, value: number, } } | { "Int": { title: S, field_name: S, default: number, value: number, min: number | null, max: number | null, } } | { "List": { title: S, field_name: S, size: ListSize<S>, ltype: Literal, } };
