// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FilterInfo } from "../../src-tauri/bindings/FilterInfo";
import type { MetaGenerator } from "../../src-tauri/bindings/MetaGenerator";
import type { MetaSink } from "../../src-tauri/bindings/MetaSink";

export type GraphMetadata = { generators: Array<MetaGenerator>, filters: Array<FilterInfo>, sinks: Array<MetaSink>, };
