// Re-export all generated types
// The individual files are auto-generated by ts-rs from Rust structs.
// Do not edit the generated files — modify the Rust types and run `npm run generate-types`.

export type { AudioSummary } from "./AudioSummary";
export type { FrequencyData } from "./FrequencyData";
export type { SpectrogramData } from "./SpectrogramData";
export type { SpectrumData } from "./SpectrumData";
export type { WaveformData } from "./WaveformData";

export interface AudioFileInfo {
    name: string;
    size: number;
    type: string;
}