// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Spectrogram (STFT) for a time window (Phase 2 response).
 * `data[time_index][freq_bin]` = magnitude.
 */
export type SpectrogramData = { data: Array<Array<number>>, start_time: number, end_time: number, time_bins: number, freq_bins: number, sample_rate: number, };
