site_name: rustic-py
docs_dir: docs
theme:
  name: material
  palette:
    scheme: slate
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [python]
          options:
            show_source: true
            show_root_heading: true
extra:
  version:
    provider: mike
nav:
  - Home: index.md
  - API Reference: api.md
