[package]
name = "rustic-meta"
description = "Metadata structures for Rustic"
version = "0.1.0"
edition = "2024"

[dependencies]
proc-macro2 = "1.0.94"
quote = "1.0.40"
serde = { version = "1.0.219", features = ["derive"] }
