[package]
name = "analyser"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.32", features = ["derive"] }
colog = "1.3.0"
log = "0.4.27"
plotters = "0.3.7"
rustfft = "6.2.0"
symphonia = "0.5.4"
