[build]
# The index HTML file to drive the bundling process.
target = "index.html"
# Build in release mode.
release = false
# The output dir for all final assets.
dist = "dist"
# The public URL from which assets are to be served.
public_url = "/"

# External Cargo.toml directory.
# cargo = "src-tauri"

# Automatically trigger a rebuild whenever a change is detected.
watch = true

[serve]
# The address to serve on.
address = "127.0.0.1"
# The port to serve on.
port = 1420
# Open a browser tab once the initial build is complete.
open = false

[clean]
# Optionally perform a cargo clean.
cargo = true

[tools]
# Use the latest version of wasm-bindgen.
wasm_bindgen = "0.2.100"
