[package]
name = "rustic-derive"
description = "Macros for generating filter metadata"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
convert_case = "0.8.0"
proc-macro2 = "1.0.94"
quote = "1.0.39"
syn = "2.0.99"
